### ISSUE TITLE
Cannot start service monero-miner:

### ISSUE THREAD

**Issue by Nakzz** [giansalex/monero-miner-docker#3]
Cannot start service monero-miner: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "-u 86rvtjFAS1uPukGSJKR4KZG7Qq9HKsofJBT16aVFyYX3GD9YTqUrzTEY4Q44FnZZCaHAse4DwQzdQ96TLd9pUvmtCqR1WvX": executable file not found in $PATH: unknown

**Comment by giansalex** [comment]
@Nakzz , you can use this command:
 ```bash
 docker run -d giansalex/monero-miner /xmr/xmrig \
     -o pool.supportxmr.com:3333 \
     -u <YOUR_WALLET> \
     -k  \
     --cpu-priority=2
 ```
