### ISSUE TITLE
Time to get the reward

### ISSUE THREAD

**Issue by apexli** [giansalex/monero-miner-docker#4]
Hi I am testing the xmr mining on 2Vcpu and 4 gb ram. After running the docker image with our wallet address how much time does it take to reflect it in our account.

**Comment by giansalex** [comment]
You can use this [formula](https://monero.stackexchange.com/a/3330)

For get your hash rate https://xmrig.com/benchmark
Current params. 
```text
network hash rate:         NHR  = 2.52 GH/s
blocks per day:            B    = 699
block reward:              Rew  = 1.03 XMR
````
[source](https://bitinfocharts.com/monero/)

**Comment by giansalex** [comment]
I added a [tools section](https://github.com/giansalex/monero-miner-docker#miner-tools). And [this tool](https://www.coinwarz.com/mining/monero/calculator) can help you.
